### ISSUE TITLE
Add Conditional Background Colors for Feedback Alerts

### ISSUE THREAD

**Issue by shubhankertiwari8** [ContriHUB/NoteSphere#1]
# Current and expected behaviour

**In the current implementation displays alerts after adding or deleting feedback, but the alerts lack background color to indicate the status of the operation. To improve user experience, you can conditionally style these alerts based on the type of operation:**

**1.When feedback is successfully added, the alert message "Added successfully" should appear with a green background to indicate 
       success.
   2.Similarly, when feedback is deleted, the alert message should be displayed with a red background to signal deletion.**

### Steps to reproduce

1. Login/Signup: Start by either logging in or signing up using the form provided.
2. Homepage Redirection: Upon successful login or signup, you will be redirected to the homepage.
3. Add Feedback: On the homepage, enter the title, description, and tag for your feedback in the provided form.
4. Submit Feedback: Click the "Add your feedback" button to submit your feedback. Once submitted, the feedback will appear on the screen.
5. Visual Feedback Confirmation: After adding the feedback, an alert is displayed at the top of the screen to confirm the action. However, the alert currently appears with a colorless (transparent) background.
6. Deleting Feedback: Similarly, when you click the "Delete" button on any feedback, a colorless alert is displayed, indicating the successful deletion of the feedback.

**While adding the feedback**
![Adding a feedback](https://github.com/user-attachments/assets/38a729db-e76a-43fd-91de-4b1dfb5ef7fd)

**While deletion of feedback**
![Deleting a feedback](https://github.com/user-attachments/assets/5859c63e-651d-4679-94c6-3396a8bb7bde)
 
**Expected**
![refrence](https://github.com/user-attachments/assets/1c259525-1932-4c4d-af84-e843a340a60e)
 
**Note: The behaviour of alert is as expected in case of logging in sign up etc.**

**Comment by Vaishnavi1047** [comment]
@shubhankertiwari8 can i work on this issue as it requires just a slight modification in alert component

**Comment by Ayush5071** [comment]
@shubhankertiwari8 can you please assign this issue to me .
