### ISSUE TITLE
Enhance NoteSphere UI with Dynamic Styling and Improved User Experience

### ISSUE THREAD

**Issue by shubhankertiwari8** [ContriHUB/NoteSphere#2]
### Description
The current frontend UI of NoteSphere lacks visual appeal and dynamic interaction, leading to a less engaging user experience. To improve the overall aesthetics and usability, the following enhancements are required:

1. **Dynamic Color Scheme:** Introduce a vibrant and dynamic color palette that aligns with modern design principles. Implement a color scheme that not only improves readability but also creates a visually appealing interface. Use contrasting colors for different sections and status alerts (e.g., success, error) to make the UI more intuitive.
2. **Responsive Design:** Ensure the application is fully responsive, providing an optimized experience across various devices, including desktops, tablets, and mobile phones. Flexbox or CSS Grid can be used for better layout adaptability.
3. **Feedback and Alerts:** Dynamically style alert messages and feedback using consistent colors (e.g., green for success, red for error), enhancing the visual response to user actions.
4. **Accessibility:** Consider accessibility best practices by ensuring sufficient contrast ratios, larger clickable areas, and using semantic HTML where possible to improve overall accessibility.
5. **Improved CSS Styling:** The current CSS is quite minimal and lacks structure. Refactor the CSS to include better layout management, spacing, and element alignment. Introduce hover effects, transitions, and animations where appropriate to make interactions feel smoother and more responsive.
6. **UI Components:** Replace bland and static elements with modern, interactive UI components.

### Few Examples

- Use buttons with hover states and transitions for a more interactive feel.
- Introduce modal pop-ups for actions like adding or editing notes instead of using basic forms.
- Use cards or grids to display notes in a more organized and visually appealing way, replacing plain lists.
- Implement tooltips and contextual hints to guide users through actions.

**Home Page**
![home](https://github.com/user-attachments/assets/865ed704-eb0e-4ccd-bffe-98d80446cd4c)

**Login Page**
![login](https://github.com/user-attachments/assets/9504d00d-3915-4652-b016-beaea8b496fb)

**Signup Page**
![signup](https://github.com/user-attachments/assets/53334746-6934-41e8-baaa-6f5376a037a4)

**Note: Use of Tailwind CSS and bootstrap is recommended**

**Comment by Vaishnavi1047** [comment]
@shubhankertiwari8 we have to make ui for all 3 pages?

**Comment by shubhankertiwari8** [comment]
@Vaishnavi1047 Yes that is the task

**Comment by shubhankertiwari8** [comment]
Although use of Tailwind CSS is recommended its not at all necessary if you implement changes using Tailwind you may receive bonus points

**Comment by Vaishnavi1047** [comment]
@shubhankertiwari8 request submitted for assignment

**Comment by Vaishnavi1047** [comment]
![Screenshot 2024-10-09 114152](https://github.com/user-attachments/assets/7b965beb-f178-47b8-a710-b3759b3b39db)
i am thinking of something like this using tailwind

**Comment by shubhankertiwari8** [comment]
@Vaishnavi1047 Hmm it is a bit more simplistic try to explore more as it looks like you have added a dark mode and nothing much has changed 
**Just to give you an idea**
![example](https://github.com/user-attachments/assets/5108d7d9-f755-4aea-b9f8-52ef5ee41fba)
This is just an example don't follow it but you get an idea of what to do

**Comment by Vaishnavi1047** [comment]
the project doesnot have tailwind ? @shubhankertiwari8

**Comment by shubhankertiwari8** [comment]
@Vaishnavi1047 No tailwind has not been used

**Comment by Vaishnavi1047** [comment]
ohk i am then setting it up in the project

**Comment by Vaishnavi1047** [comment]
![Screenshot 2024-10-10 015458](https://github.com/user-attachments/assets/58fcfec6-dc8a-4de0-a9ed-ed43d9f32c90)
![Screenshot 2024-10-10 021400](https://github.com/user-attachments/assets/284addb5-15c1-4bce-801f-3fc2d758b76a)
![Screenshot 2024-10-10 021435](https://github.com/user-attachments/assets/d2b77d70-5c2c-445e-9677-93899255f8ad)
![Screenshot 2024-10-10 021453](https://github.com/user-attachments/assets/15db7065-019f-4115-87dd-5f467c91f7ed)
@shubhankertiwari8 can i push it?
