### ISSUE TITLE
"Vote" Page for User Polling

### ISSUE THREAD

**Issue by shubhankertiwari8** [ContriHUB/NoteSphere#21]
# Description

Create a new page accessible through the navbar named **"Vote"** where users can cast their votes on a query question created by the admin to gather their input. Only the admin is capable of creating such polls, and the results should be displayed automatically after a fixed time specified by the admin. Admins cannot cast votes, and users cannot create polls.

### Page Features:

- **Admin Only Poll Creation**: The page should have two distinct functionalities for the admin:
  - **Poll Creation**: The admin can create polls and set a timer for result declaration.
  - **Result Declaration**: Results should be displayed after the specified time in a format chosen by the admin (e.g., bar chart, pie chart, etc.).
  
- **User Voting**: Users should only be able to cast their votes. Once the user casts their vote, the poll should disappear for that user, ensuring that they cannot vote again.

- **Real-Time Poll Monitoring for Admin**: Admins should be able to monitor live voting progress in the form of progress bars, which update dynamically before the timer expires.

- **Result Display**: Once the timer expires, the voting progress bars should disappear, and the final results should be displayed in the selected format (bar chart, pie chart, etc.).

- **Result Removal**: Admins can set an expiration period (e.g., 1 week) after which the poll results will be automatically removed from the "Vote" page.

We want to gather structured feedback from users via polls, but maintain control over the creation and management of these polls by restricting it to admins. This prevents clutter and ensures a structured flow of information.

This feature is important to create a controlled polling system where users can participate in voting while keeping poll creation and management under the admin's authority.

1. A **"Vote"** page that allows:
   - **Admins**: To create polls, set timers for result declaration, and view real-time voting progress.
   - **Users**: To cast a vote, after which the poll will disappear for them until the timer expires and results are shown.

2. The **results** should be displayed automatically in a format chosen by the admin (bar chart, pie chart, etc.).

3. Admins should have the ability to **manage poll results**, including setting an expiration date (e.g., 1 week) for automatic removal of results.

We considered allowing users to suggest poll topics, but keeping poll creation restricted to admins ensures simplicity and control. We also considered adding more result visualization formats (e.g., line graphs).

**NOTE: The results can be shown in a format of the admin’s choosing (e.g., bar chart, pie chart, etc.). How the result is displayed is flexible—it can either appear on the same "Vote" page (e.g., at the top in a separate section) or on a separate "Result" page. Please ensure the design aligns with the current CSS and UI of Notesphere.**

**Comment by RITIK-CHAUDHRY** [comment]
i have applied through contrihub please assign issue to me @shubhankertiwari8

**Comment by Vaishnavi1047** [comment]
this issue is assigned to me

**Comment by Vaishnavi1047** [comment]
@shubhankertiwari8 can u pls check the pr sir

**Comment by Vaishnavi1047** [comment]
@shubhankertiwari8 check discord pls
