### ISSUE TITLE
Announcement Page 

### ISSUE THREAD

**Issue by shubhankertiwari8** [ContriHUB/NoteSphere#22]
# Description

Create a new page accessible through the navbar named **"Announcements"**, where admins can post important announcements, and users can view them in real-time. Only the admin will have permission to create and post announcements, while users can only read them. The announcements should be sorted chronologically by date and time (most recent at the top) and remain permanently visible unless manually removed by the admin.

### Admin Posting:
- Admins can post announcements on the **"Announcements"** page, which will immediately appear for all users in real-time.
- Before an announcement is posted, the admin should have an option to confirm and review the content before publishing.

### Real-Time Updates:
- The page should update in real-time, so users can see new announcements as soon as they are posted, without needing to refresh the page.
- Users should be notified of any new, unread announcements with a clear indication (e.g., a notification badge on the "Announcements" page link in the navbar).

### User View:
- Users can only read the announcements and cannot post or edit them.
- Announcements should be permanently stored and visible to all users unless manually removed by the admin.
- Announcements should be sorted in descending order of date and time, ensuring the most recent announcements appear at the top.

This feature is intended to create a centralized place for admins to share important updates, announcements, and notifications with users in real-time. Users need to be informed immediately when a new announcement is posted and have a clear way to distinguish between read and unread announcements.

Providing a real-time, permanent announcement page ensures that important information from the admin is effectively communicated to all users. It also prevents users from missing important updates by ensuring that unread announcements are highlighted.

### Announcement Page:
- Admins can post and manage announcements.
- Users can view announcements but cannot interact or post themselves.

### Real-Time Notifications:
- Users should see real-time updates when new announcements are posted, and there should be a clear indicator of unread announcements (e.g., a badge or highlight in the navbar).

### Chronological Sorting:
- Announcements should be sorted by date and time, with the newest appearing at the top of the page.

We considered creating a notification system or integrating announcements with other forms of communication, but a dedicated page keeps all updates in one clear and accessible place.

**Comment by nxd010** [comment]
Hi @shubhankertiwari8, I would like to work on this. Can you assign me this since it has not been updated in Contrihub yet?

**Comment by RITIK-CHAUDHRY** [comment]
i have applied through contrihub please assign issue to me @shubhankertiwari8

**Comment by RITIK-CHAUDHRY** [comment]
@shubhankertiwari8 is this issue open? if yes please assign me'

**Comment by Gprakhar141** [comment]
Thanks for assigning, I will start working on it.

**Comment by Gprakhar141** [comment]
@shubhankertiwari8 Do I have to implement Socket for Real Time Notifications???

**Comment by Gprakhar141** [comment]
@shubhankertiwari8 I have raised a PR for this issue please review it.
