### ISSUE TITLE
Implement User Notification for Unauthorized Homepage Access

### ISSUE THREAD

**Issue by shubhankertiwari8** [ContriHUB/NoteSphere#3]
# Description
Currently, when a user attempts to access the homepage of NoteSphere without being logged in or signed up, they are redirected to the login/signup page without any warning or notification. This can lead to confusion and frustration, as users may not understand why they cannot access the homepage.

To enhance user experience and clarity, the following improvements are recommended:

1. **User Awareness Prompt:** Before redirecting the user to the login/signup page, display a clear and informative alert or modal that explains the situation. This prompt should communicate that access to the homepage requires user authentication.
2. **Alert/Modal Design:**
- Alert Option: A temporary alert message can be displayed at the top of the screen, indicating the need to log in to access the homepage. This alert should be visually distinct and easy to dismiss.
- Modal Option: A modal dialog can be used to provide a more comprehensive message. The modal should include:
- A brief message explaining that authentication is required.
- Buttons for users to proceed to the login/signup page or to cancel the action and remain on the current page.
3. **User-Friendly Messaging:** The notification should be concise yet informative. For example:
- "Access Denied: You must be logged in to view the homepage. Please log in or sign up to continue."
- Include clear buttons for Login and Sign Up along with a Cancel option to give users the flexibility to choose their next step.
4. **Implementation Details:**
- Use React state management to control the display of the alert/modal based on user actions.
- Ensure that the alert/modal has a user-friendly design that aligns with the overall aesthetic of NoteSphere.
- Test the functionality to ensure that it behaves correctly across different scenarios, including navigating directly to the homepage or using browser refresh.

### By implementing these changes, users will have a clearer understanding of why they cannot access the homepage, improving the overall usability of NoteSphere and reducing potential frustration.

An alternative approach to managing homepage access is to hide or disable the homepage link in the navbar for users who are not logged in. This way, unauthorized users will not be able to attempt to access the homepage directly, preventing confusion and enhancing the overall user experience. By conditionally rendering the link based on authentication status, we can ensure that users are aware of their need to log in or sign up before accessing the homepage.

**Comment by Himanshuadv** [comment]
Could you please assign this issue to me?

**Comment by krVatsal** [comment]
Issue assigned, Working on it!

**Comment by Himanshuadv** [comment]
Hi! I noticed that there is an open pull request related to this issue. I’m really interested in working on it and I would like to contribute. If the current PR doesn't address all the requirements or isn't active anymore, could I please be assigned to this issue? I’d be happy to either continue from where it left off or provide improvements if needed.

Thank you!

**Comment by hexwhiz** [comment]
@shubhankertiwari8 can I work on this issue? I have an assignment request through contrihub.

**Comment by RITIK-CHAUDHRY** [comment]
if someone is not working on this may @shubhankertiwari8 assign me this

**Comment by hexwhiz** [comment]
@shubhankertiwari8 please review my PR. I think the issue have been resolved with that.
